const overarching_story = {
    "main_story": `In a world where chaos reigns, the fate of all existence rests on the shoulders of a chosen few. As the chosen specter, you are tasked with a monumental mission - to become the next God of Creation, the Kami, and restore order to the universe. The task at hand is not an easy one. The God of Destruction has wrought havoc across countless worlds, and the negative energy that he has dispersed has made the task of becoming the next Kami even more challenging.

    With the fate of the universe hanging in the balance, you must travel through various anime worlds, including Naruto, Bleach, and One Piece, and work with their protagonists to resonate and destroy the negative energy. But the journey ahead is perilous, and there are other candidates vying for the title of Kami. You must fight against them, too, and defeat them to prove that you are the rightful heir to the throne of the God of Creation.
    
    With the power of the Kami's energy coursing through your veins, you embark on a journey of self-discovery, growth, and conquest. Will you emerge victorious, or will the forces of destruction prevail? The future of the universe rests in your hands.`,
    "main_story_short_description": "In a chaotic universe, you, as the chosen specter, must become the next God of Creation, the Kami, and restore order. With the God of Destruction's negative energy wreaking havoc, you must travel through various anime worlds, resonate with their protagonists, and destroy the negative energy. Fighting other Kami candidates, your journey of self-discovery and conquest holds the future of the universe in the balance.",

}

const lore = {
    "why_anime_worlds_exist_long_description": `The God of Creation found it to be an enjoyable pastime to spread the concepts of other worlds as ideas in the minds of individuals scattered throughout the universe. In doing so, the God of Creation hoped to inspire creativity and ingenuity among the mortals, leading them to achieve great feats of strength and courage. The specters, being chosen by the God of Creation, are imbued with the knowledge of these other worlds, which they have acquired through books, manga, and anime. This familiarity with other worlds is an asset in their quest to become the next Kami, as they are able to navigate through these worlds with greater ease and connect with the protagonists of these stories more effectively. The God of Creation's legacy lives on in the specters, who continue to explore and draw inspiration from the diverse range of worlds that the God of Creation has shared with them.`,
    "why_anime_worlds_exist_short_description": `The God of Creation spread the concepts of other worlds as ideas in the minds of mortals scattered throughout the universe. The specters were chosen by the God of Creation and are imbued with the knowledge of these other worlds, acquired through books, manga, and anime. This familiarity with other worlds aids them in their quest to become the next Kami and connect with the protagonists of these stories.`
}